name: Bug Report
description: Create a report to help us fix a bug in aur-sentry
title: "fix: [Short bug summary]"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for reporting an issue! Please provide as much context as possible.
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: Steps or commands to reproduce the behavior.
      placeholder: |
        1. Run 'safeaur ...' or 'cargo test'
        2. Encounter error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Terminal Output
      render: shell
